apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: vote
  labels:
    name: vote-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      name: vote-app
      labels:
        app: vote
    spec:
      containers:
      - name: vote-app
        image: dockersamples/examplevotingapp_vote
        ports:
         - containerPort: 80
